In [7]:
import pandas as pd

dane = pd.read_csv('data/airbnb.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'data/airbnb.csv'

In [58]:
dane.head(2)

,Unnamed: 0,listing_id,name,host_id,host_name,neighbourhood_full,coordinates,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365,rating,number_of_stays,5_stars,listing_added
0,0,13740704,"Cozy,budget friendly, cable inc, private entra...",20583125,Michel,"Brooklyn, Flatlands","(40.63222, -73.93398)",Private room,45$,10,2018-12-12,0.7,85,4.100954,12.0,0.609432,2018-06-08
1,1,22005115,Two floor apartment near Central Park,82746113,Cecilia,"Manhattan, Upper West Side","(40.78761, -73.96862)",Entire home/apt,135$,1,2019-06-30,1.0,145,3.367600,1.2,0.746135,2018-12-25

In [59]:
dane.shape

(10019, 17)

In [60]:
dane.isna().sum()

Unnamed: 0               0
listing_id               0
name                     5
host_id                  0
host_name                2
neighbourhood_full       0
coordinates              0
room_type                0
price                  238
number_of_reviews        0
last_review           2075
reviews_per_month     2075
availability_365         0
rating                2075
number_of_stays       2075
5_stars               2075
listing_added            0
dtype: int64

In [1]:
#dane['price'] = dane['price'].str.strip("$")
#dane['price'] =head()
dane['price'] = dane['price'].astype('float')
dane['price'].mean()

NameError: name 'dane' is not defined

In [ ]:
dane.head(3)

,Unnamed: 0,listing_id,name,host_id,host_name,neighbourhood_full,coordinates,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365,rating,number_of_stays,5_stars,listing_added
0,0,13740704,"Cozy,budget friendly, cable inc, private entra...",20583125,Michel,"Brooklyn, Flatlands","(40.63222, -73.93398)",Private room,45.0,10,2018-12-12,0.7,85,4.100954,12.0,0.609432,2018-06-08
1,1,22005115,Two floor apartment near Central Park,82746113,Cecilia,"Manhattan, Upper West Side","(40.78761, -73.96862)",Entire home/apt,135.0,1,2019-06-30,1.0,145,3.367600,1.2,0.746135,2018-12-25
2,2,21667615,Beautiful 1BR in Brooklyn Heights,78251,Leslie,"Brooklyn, Brooklyn Heights","(40.7007, -73.99517)",Entire home/apt,150.0,0,NaN,NaN,65,NaN,NaN,NaN,2018-08-15

In [ ]:
avg = dane['price'].mean()
dane['price'].fillna(avg)

0         45.0
1        135.0
2        150.0
3         86.0
4        160.0
         ...
10014    105.0
10015    125.0
10016    100.0
10017    450.0
10018     90.0
Name: price, Length: 10019, dtype: float64

In [ ]:
dane.isna().sum() #powinno dla price byc 0 bledow (brakow)

Unnamed: 0               0
listing_id               0
name                     5
host_id                  0
host_name                2
neighbourhood_full       0
coordinates              0
room_type                0
price                  238
number_of_reviews        0
last_review           2075
reviews_per_month     2075
availability_365         0
rating                2075
number_of_stays       2075
5_stars               2075
listing_added            0
dtype: int64